# Use this for testing the API endpoints directly from within the IDE.
@Claims_API_HostAddress = https://localhost:7052

GET {{Claims_API_HostAddress}}/Claims/
Accept: application/json

###

GET {{Claims_API_HostAddress}}/Covers/
Accept: application/json
